#makefile proj2

CC = gcc
CFLAGS = -Wall -Wextra -Werror -ansi -pedantic -o
TARGET = proj2

all:
	@echo "Compiling..."
	$(CC) $(CFLAGS) $(TARGET) *.c *.h
	@echo "SUCCESS"
clean:
	@echo "Cleaning..."
	rm $(TARGET)
	@echo "SUCCESS"